### ISSUE TITLE
source-less minified javascripts all over the source

### ISSUE THREAD

**Issue by onlyjob** [X2Engine/X2Engine#41]
All over the source tree there are source-less minified javascript and .css files:

 `x2engine/js/lib/jquery-migrate-1.2.1.js`
 `x2engine/js/lib/moment-with-locales.min.js`
 `x2engine/js/modcoder_excolor/jquery.modcoder.excolor.js`
 `x2engine/js/jquery-1.6.2.min.js`
 `x2engine/js/jquery-ui-1.8.16.custom.min.js`
 `x2engine/js/jquery.fullscreen-min.js`
 `x2engine/js/jstorage.min.js`
 `x2engine/js/modernizr.custom.66175.js`
 `x2engine/css/bootstrap/bootstrap.min.css`

and many others. Minified javascripts (and .css) are effectively the same as pre-compiled binaries -- un-readable, non-modifiable and non-distributable in [Debian](http://debian.org).
It is a bad practice to commit minified files just like it is a bad practice to commit other pre-compiled binaries.

Some of those minified files are redundant (when original uncompressed file exist) and some appears to be customised (not the same as original 3rd party file) but without source.

Please consider removing all minified files and replacing them with original uncompressed files.

Thanks.

**Comment by x2zulu** [comment]
We will take a look at this to see if we can make it easier. 
Thanks

**Comment by onlyjob** [comment]
Please keep this bug open until this issue is resolved. Thanks.
