### ISSUE TITLE
non-free images

### ISSUE THREAD

**Issue by onlyjob** [X2Engine/X2Engine#42]
According to [LICENSE.txt](../blob/master/x2engine/images/LICENSE.txt) files in `x2engine/images/*` are licensed under non-free  _CC-BY-NC-ND-3.0_ license prohibiting commercial use and modification. Presence of such files makes the whole source archive non-distributable. Therefore X2Engine is not suitable for inclusion to [Debian](http://debian.org).

Please consider re-licensing those image under free license like _CC-BY-SA-3.0_ (or higher version). Alternatively those proprietary logos can be removed from source tree.

Let me stress the importance of this issue again: presence of images with non-commercial restriction in source archive makes X2Engine community edition _non-free_ which invalidates the claim that the latter is "free and open source".

**Comment by x2zulu** [comment]
Yes, we have removed most of these images in a future release. 

What is your relation to Debian? Looks like you work for Odoo CRM/ERP. Can you provide more detail on your Debian credentials. 

Thanks.

**Comment by onlyjob** [comment]
On Thu, 23 Apr 2015 14:07:06 John Roberts wrote:
> Yes, we have removed most of these images in a future release.

Thanks, but I'm not sure if removing "most of those images" would be 
sufficient. How about removing all of them?


> What is your relation to Debian?

I am a Debian Developer.


> Looks like you work for Odoo CRM/ERP.

No, I was just working on prospective packaging of Odoo for Debian.
I did not sign their CLA etc. I was merely forwarding problems I've happened 
to notice... Same as with X2Engine.


> Can you provide more detail on your Debian credentials.

Why? Our development is public, we do not hide anything. You can find all my 
activity online.

-- 
Cheers,
 Dmitry Smirnov


P.S. As you can imagine I'm not quite happy about removing my bug reports 
without a trace... What's wrong with having a public bug tracker on GitHub? 
The more difficult you make it to communicate the less likely a potential 
contributor would try to help...

---

Our difficulties and our dangers will not be removed by closing our eyes on
them.
        -- Winston Churchill

**Comment by x2zulu** [comment]
Hi Dmitry,

Ok, I did not see you listed on the Debian website as a contributor. What
do you work on? Can you send me a link to your work? Thanks for sharing.

X2Community.com is better place to work with us. Because we use a lot of
different download sites, each with their own issue repository - to many
places to manage. We did replace our in-house created images with another
image library that is easier, so no worries.

Best,
John

On Thu, Apr 23, 2015 at 4:06 PM, Dmitry Smirnov <notifications@github.com>
wrote:

> On Thu, 23 Apr 2015 14:07:06 John Roberts wrote:
> > Yes, we have removed most of these images in a future release.
>
> Thanks, but I'm not sure if removing "most of those images" would be
> sufficient. How about removing all of them?
>
>
> > What is your relation to Debian?
>
> I am a Debian Developer.
>
>
> > Looks like you work for Odoo CRM/ERP.
>
> No, I was just working on prospective packaging of Odoo for Debian.
> I did not sign their CLA etc. I was merely forwarding problems I've
> happened
> to notice... Same as with X2Engine.
>
>
> > Can you provide more detail on your Debian credentials.
>
> Why? Our development is public, we do not hide anything. You can find all
> my
> activity online.
>
> --
> Cheers,
> Dmitry Smirnov
>
>
> P.S. As you can imagine I'm not quite happy about removing my bug reports
> without a trace... What's wrong with having a public bug tracker on
> GitHub?
> The more difficult you make it to communicate the less likely a potential
> contributor would try to help...
>
> ---
>
> Our difficulties and our dangers will not be removed by closing our eyes on
> them.
> -- Winston Churchill
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/X2Engine/X2Engine/issues/42#issuecomment-95742592>.
>



-- 




*John Roberts *
X2Engine Inc.
Santa Cruz, California USA
http://www.x2engine.com
Phone: 1-831-222-5333 ext.111
Email: john@x2engine.com
Skype: x2engine

**Comment by onlyjob** [comment]
Hi John,

On Thu, 23 Apr 2015 16:18:13 John Roberts wrote:
> What do you work on? Can you send me a link to your work?

https://qa.debian.org/developer.php?login=onlyjob

There are too many links to send. Why don't you use a search engine?

Why are you curious about my Debian work?

-- 
Cheers,
 Dmitry Smirnov

---

Success consists of going from failure to failure without loss of enthusiasm.
        -- Winston Churchill

**Comment by x2zulu** [comment]
Thank you, because I run a cluster of custom built Debian servers in a
local datacenter. It is the very best OS I believe.

I did not know X2Engine was being included in Debian, sounds great.

X2Engine code base was started five years ago and has been in continuous
development by four to five developers. All of the development, IT
infrastructure, office, and operational costs of have been funded by
X2Engine Inc. Our goal is to be the Debian of CRM.

I know most folks are not crazy about the GPL v3 Affero, but I believe it
is best for development teams that spend more the 70% of their time on user
interface design and construction. You would be amazed how many people just
want to rebrand and sell the app as if they wrote it themselves without any
intenton of contributing anything of value in return. I know its ok, and
fair, but I not have to like it as the developer of the software. I believe
that if our code was 90% backend then I would not care so much.

We did switch out our custom images for an open library two dot releases
back, 5.1 but did not take out the old images and restrictive cc license.
We are doing that now for 5.7 in the next two weeks.

Thank you for Debian,
John




On Thu, Apr 23, 2015 at 4:32 PM, Dmitry Smirnov <notifications@github.com>
wrote:

> Hi John,
>
> On Thu, 23 Apr 2015 16:18:13 John Roberts wrote:
> > What do you work on? Can you send me a link to your work?
>
> https://qa.debian.org/developer.php?login=onlyjob
>
> There are too many links to send. Why don't you use a search engine?
>
> Why are you curious about my Debian work?
>
> --
> Cheers,
> Dmitry Smirnov
>
> ---
>
> Success consists of going from failure to failure without loss of
> enthusiasm.
> -- Winston Churchill
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/X2Engine/X2Engine/issues/42#issuecomment-95747047>.
>



-- 




*John Roberts *
X2Engine Inc.
Santa Cruz, California USA
http://www.x2engine.com
Phone: 1-831-222-5333 ext.111
Email: john@x2engine.com
Skype: x2engine

**Comment by onlyjob** [comment]
On Thu, 23 Apr 2015 16:58:09 John Roberts wrote:
> Thank you, because I run a cluster of custom built Debian servers in a
> local datacenter. It is the very best OS I believe.

Thank you for your kind words. I do share your belief that Debian is the best 
GNU/Linux distribution.


> I did not know X2Engine was being included in Debian, sounds great.

It is not going to be included (yet) primarily because of the bugs I've 
submitted.
As far as I'm aware nobody is working on packaging of X2Engine for Debian.

At the moment X2Engine is not on my list of software to package.
FYI I'm not happy with Odoo too so I won't continue its packaging efforts...


> X2Engine code base was started five years ago and has been in continuous
> development by four to five developers. All of the development, IT
> infrastructure, office, and operational costs of have been funded by
> X2Engine Inc. Our goal is to be the Debian of CRM.

Great. :) I wish you all the best.
IMHO there is a lot you can do to make X2Engine more attractive. Good 
license/copyright coverage is crucial but also more open development (no bulk 
commits to GitHub), easy access to bug tracker and less crippled community 
edition might help.


> I know most folks are not crazy about the GPL v3 Affero, but I believe it
> is best for development teams that spend more the 70% of their time on user
> interface design and construction.

I agree. AGPL-3 is great and IMHO it is in software's best interests to have a 
good license to protect and encourage contribution.


> You would be amazed how many people just
> want to rebrand and sell the app as if they wrote it themselves without any
> intenton of contributing anything of value in return.

Well, isn't that what Ubuntu is doing with Debian? ;) I feel the pain.


> I know its ok, and
> fair, but I not have to like it as the developer of the software. I believe
> that if our code was 90% backend then I would not care so much.

I think those leeche(r)s always miss something more important -- a 
collaboration. One of the reasons why I don't like derivatives is because they 
usually claim a lot of "added value" but in reality they are just disconnected 
from development and therefore slow down propagation of fixes, productive work 
on bug tracker, contribution etc... Not to mention giving fair credits to 
those who did most of the hard work...


> We did switch out our custom images for an open library two dot releases
> back, 5.1 but did not take out the old images and restrictive cc license.
> We are doing that now for 5.7 in the next two weeks.

Nice. Thanks for doing that. It is important.


> Thank you for Debian,

:)  Pleasure to read this. Thank you.

-- 
Cheers,
 Dmitry Smirnov

P.S. please feel free to email directly to me -- I hope it would be more 
convenient than communicating through GitHub.

**Comment by x2zulu** [comment]
Hi Dmitry,

Nice. I am happy to help in any way to make packing easier, including
developing a Debian package ourselves. I will turn the issue tracker back
on.

As a reference Webmin\Virtualmin has an X2Engine packager for Debian
deployment. This is what we use for our hosting platform.
https://www.virtualmin.com/documentation/install-scripts

When, if you are ready look at this again please feel free to contact me.

John






On Thu, Apr 23, 2015 at 5:44 PM, Dmitry Smirnov <notifications@github.com>
wrote:

> On Thu, 23 Apr 2015 16:58:09 John Roberts wrote:
> > Thank you, because I run a cluster of custom built Debian servers in a
> > local datacenter. It is the very best OS I believe.
>
> Thank you for your kind words. I do share your belief that Debian is the
> best
> GNU/Linux distribution.
>
>
> > I did not know X2Engine was being included in Debian, sounds great.
>
> It is not going to be included (yet) primarily because of the bugs I've
> submitted.
> As far as I'm aware nobody is working on packaging of X2Engine for Debian.
>
> At the moment X2Engine is not on my list of software to package.
> FYI I'm not happy with Odoo too so I won't continue its packaging
> efforts...
>
>
> > X2Engine code base was started five years ago and has been in continuous
> > development by four to five developers. All of the development, IT
> > infrastructure, office, and operational costs of have been funded by
> > X2Engine Inc. Our goal is to be the Debian of CRM.
>
> Great. :) I wish you all the best.
> IMHO there is a lot you can do to make X2Engine more attractive. Good
> license/copyright coverage is crucial but also more open development (no
> bulk
> commits to GitHub), easy access to bug tracker and less crippled community
> edition might help.
>
>
> > I know most folks are not crazy about the GPL v3 Affero, but I believe it
> > is best for development teams that spend more the 70% of their time on
> user
> > interface design and construction.
>
> I agree. AGPL-3 is great and IMHO it is in software's best interests to
> have a
> good license to protect and encourage contribution.
>
>
> > You would be amazed how many people just
> > want to rebrand and sell the app as if they wrote it themselves without
> any
> > intenton of contributing anything of value in return.
>
> Well, isn't that what Ubuntu is doing with Debian? ;) I feel the pain.
>
>
> > I know its ok, and
> > fair, but I not have to like it as the developer of the software. I
> believe
> > that if our code was 90% backend then I would not care so much.
>
> I think those leeche(r)s always miss something more important -- a
> collaboration. One of the reasons why I don't like derivatives is because
> they
> usually claim a lot of "added value" but in reality they are just
> disconnected
> from development and therefore slow down propagation of fixes, productive
> work
> on bug tracker, contribution etc... Not to mention giving fair credits to
> those who did most of the hard work...
>
>
> > We did switch out our custom images for an open library two dot releases
> > back, 5.1 but did not take out the old images and restrictive cc license.
> > We are doing that now for 5.7 in the next two weeks.
>
> Nice. Thanks for doing that. It is important.
>
>
> > Thank you for Debian,
>
> :) Pleasure to read this. Thank you.
>
> --
> Cheers,
> Dmitry Smirnov
>
> P.S. please feel free to email directly to me -- I hope it would be more
> convenient than communicating through GitHub.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/X2Engine/X2Engine/issues/42#issuecomment-95763727>.
>



-- 




*John Roberts *
X2Engine Inc.
Santa Cruz, California USA
http://www.x2engine.com
Phone: 1-831-222-5333 ext.111
Email: john@x2engine.com
Skype: x2engine

**Comment by onlyjob** [comment]
> Nice. I am happy to help in any way to make packing easier, including developing a Debian package ourselves.

Even outside Debian, packaging could be helpful for deployment.

> I will turn the issue tracker back on. 

Thank you. Much appreciated.

> When, if you are ready look at this again please feel free to contact me.

I'll probably have another look once new version with removed non-free images is released.

If you need to speed things up I may be available for hire.

Cheers,
  Dmitry.

**Comment by x2zulu** [comment]
Hi Dmitry,

Yes I would be interested in funding your work to make it easer to deploy
X2Engine on Debian. I agree with you the UI has gotten a bit dense with
5.0. we are working to simplify things again with a large release this
summer. I am also ok with all of your work being licensed under an open
source license. I have a project underway to build custom Debian based
enterprise level deployment images for AmazonAWS and Google Cloud Compute.
I have one engineer assigned to this project and his is pretty close to
having our AWS auto installer done. I am also open to ideas you may have.
Do you do app work?

Regarding budget, I have a small company so many not be able to afford
corporate rates. But I believe X2Engine has a very bright future so could
be good long term thing if things go well.

I am available for a web chat if you would like to talk more.

Best,
John  - about me http://www.johnsocean.com/

On Thu, Apr 23, 2015 at 6:43 PM, Dmitry Smirnov <notifications@github.com>
wrote:

> Nice. I am happy to help in any way to make packing easier, including
> developing a Debian package ourselves.
>
> Even outside Debian, packaging could be helpful for deployment.
>
> I will turn the issue tracker back on.
>
> Thank you. Much appreciated.
>
> When, if you are ready look at this again please feel free to contact me.
>
> I'll probably have another look once new version with removed non-free
> images is released.
>
> If you need to speed things up I may be available for hire.
>
> Cheers,
> Dmitry.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/X2Engine/X2Engine/issues/42#issuecomment-95772044>.
>



-- 




*John Roberts *
X2Engine Inc.
Santa Cruz, California USA
http://www.x2engine.com
Phone: 1-831-222-5333 ext.111
Email: john@x2engine.com
Skype: x2engine

**Comment by onlyjob** [comment]
On Thu, 23 Apr 2015 19:13:02 John Roberts wrote:
> Yes I would be interested in funding your work to make it easer to deploy
> X2Engine on Debian.

Awesome. :)


> I am also ok with all of your work being licensed under an open
> source license.

It might be a good idea to use the same AGPL-3+ license to keep licensing 
simple but I'm OK with Expat too (if necessary).

Let's do packaging as per Debian standards to make it suitable to inclusion to 
Debian officially.


> I have a project underway to build custom Debian based
> enterprise level deployment images for AmazonAWS and Google Cloud Compute.
> I have one engineer assigned to this project and his is pretty close to
> having our AWS auto installer done.

Interesting.


> I am also open to ideas you may have.

Not at the moment as I have very little experience with Amazon and no 
experience with Google cloud at all...


> Do you do app work?

You mean development? Yes I do but mostly in Perl and Bash. I am illiterate in 
PHP (although I can read it and make trivial fixes) so I'm not sure how I can 
be of help.


> Regarding budget, I have a small company so many not be able to afford
> corporate rates. But I believe X2Engine has a very bright future so could
> be good long term thing if things go well.

I operate small business myself and we always treat Open Source work as  
eligible for discounts. :)

How about 25% discount to begin with? I usually charge $80 AUD per hour (plus 
GST but as international customer you won't be charged GST).

See http://raid6.com.au for rates and other info.


> I am available for a web chat if you would like to talk more.

How about email?


> John  - about me http://www.johnsocean.com/


Gorgeous blog by the way. Great photos. :)

-- 
Cheers,
 Dmitry Smirnov

P.S. Did you just disable GitHub bug tracker again? I have no secrets to 
hide...

**Comment by x2zulu** [comment]
Dmitry,
Great! Thank you. My email is john@x2engine.com. I look forward to
chatting.
John

On Thu, Apr 23, 2015 at 7:41 PM, Dmitry Smirnov <notifications@github.com>
wrote:

> On Thu, 23 Apr 2015 19:13:02 John Roberts wrote:
> > Yes I would be interested in funding your work to make it easer to deploy
> > X2Engine on Debian.
>
> Awesome. :)
>
>
> > I am also ok with all of your work being licensed under an open
> > source license.
>
> It might be a good idea to use the same AGPL-3+ license to keep licensing
> simple but I'm OK with Expat too (if necessary).
>
> Let's do packaging as per Debian standards to make it suitable to
> inclusion to
> Debian officially.
>
>
> > I have a project underway to build custom Debian based
> > enterprise level deployment images for AmazonAWS and Google Cloud
> Compute.
> > I have one engineer assigned to this project and his is pretty close to
> > having our AWS auto installer done.
>
> Interesting.
>
>
> > I am also open to ideas you may have.
>
> Not at the moment as I have very little experience with Amazon and no
> experience with Google cloud at all...
>
>
> > Do you do app work?
>
> You mean development? Yes I do but mostly in Perl and Bash. I am
> illiterate in
> PHP (although I can read it and make trivial fixes) so I'm not sure how I
> can
> be of help.
>
>
> > Regarding budget, I have a small company so many not be able to afford
> > corporate rates. But I believe X2Engine has a very bright future so could
> > be good long term thing if things go well.
>
> I operate small business myself and we always treat Open Source work as
> eligible for discounts. :)
>
> How about 25% discount to begin with? I usually charge $80 AUD per hour
> (plus
> GST but as international customer you won't be charged GST).
>
> See http://raid6.com.au for rates and other info.
>
>
> > I am available for a web chat if you would like to talk more.
>
> How about email?
>
>
> > John - about me http://www.johnsocean.com/
>
>
> Gorgeous blog by the way. Great photos. :)
>
> --
> Cheers,
> Dmitry Smirnov
>
> P.S. Did you just disable GitHub bug tracker again? I have no secrets to
> hide...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/X2Engine/X2Engine/issues/42#issuecomment-95780012>.
>



-- 




*John Roberts *
X2Engine Inc.
Santa Cruz, California USA
http://www.x2engine.com
Phone: 1-831-222-5333 ext.111
Email: john@x2engine.com
Skype: x2engine
